/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Inscrire un passager
         * @description Crée le compte puis envoie un OTP au numéro fourni. Le compte reste
         *     inutilisable tant que le téléphone n'est pas vérifié.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @description Format E.164
                         * @example +237690000000
                         */
                        phone: string;
                        /** Format: email */
                        email?: string;
                        first_name: string;
                        last_name: string;
                        /**
                         * @description Défaut `fr`. Détermine la langue de l'OTP, donc du tout
                         *     premier message reçu — avant même que le compte existe.
                         */
                        locale?: components["schemas"]["Locale"];
                    };
                };
            };
            responses: {
                /** @description OTP envoyé */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OtpChallenge"];
                    };
                };
                /** @description Numéro déjà inscrit */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                422: components["responses"]["ValidationError"];
                default: components["responses"]["DefaultError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Demander un OTP de connexion */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        phone: string;
                    };
                };
            };
            responses: {
                /** @description OTP envoyé */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OtpChallenge"];
                    };
                };
                /** @description Aucun compte pour ce numéro */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                default: components["responses"]["DefaultError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/otp/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Vérifier un OTP et ouvrir une session
         * @description L'OTP est valide 10 minutes et accepte 4 tentatives au maximum.
         *     Au-delà, il est invalidé et un nouvel envoi est nécessaire.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        phone: string;
                        code: string;
                        purpose: components["schemas"]["OtpPurpose"];
                    };
                };
            };
            responses: {
                /** @description Session ouverte */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            token: string;
                            user: components["schemas"]["User"];
                        };
                    };
                };
                /**
                 * @description Code invalide, expiré, ou nombre de tentatives dépassé.
                 *     Codes possibles — `OTP_INVALID`, `OTP_EXPIRED`, `OTP_TOO_MANY_ATTEMPTS`.
                 */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                default: components["responses"]["DefaultError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/otp/resend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Renvoyer un OTP */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        phone: string;
                        purpose: components["schemas"]["OtpPurpose"];
                    };
                };
            };
            responses: {
                /** @description OTP renvoyé */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OtpChallenge"];
                    };
                };
                /** @description Trop de demandes */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                default: components["responses"]["DefaultError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Profil de l'utilisateur courant */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                default: components["responses"]["DefaultError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Révoquer le jeton courant */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Session close */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                default: components["responses"]["DefaultError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/places/autocomplete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Autocomplétion des lieux
         * @description Propose **villes et gares**. Une gare sélectionnée résout vers sa
         *     ville : la recherche s'exécute toujours au niveau ville.
         *
         *     La comparaison est insensible aux accents et à la casse, et s'appuie
         *     sur une liste d'alias par ville. Les accents n'étant pratiquement
         *     jamais saisis sur un clavier de téléphone, une correspondance stricte
         *     échouerait sur une grande part des saisies réelles.
         */
        get: {
            parameters: {
                query: {
                    q: string;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["PlaceSuggestion"][];
                        };
                    };
                };
                default: components["responses"]["DefaultError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Rechercher des trajets
         * @description Requête centrale du produit. Le filtrage porte sur le couple
         *     **ville de départ / ville d'arrivée** : la réservation étant
         *     point-à-point, une ville d'escale ne rend pas un trajet éligible.
         *
         *     Les départs dont la fenêtre de vente en ligne est fermée
         *     n'apparaissent pas dans les résultats.
         *
         *     **Lorsque `data` est vide**, la réponse porte un bloc `suggestions`
         *     — dates proches disponibles et axes desservis au départ de la même
         *     ville. Un seul aller-retour, et le client a toujours quelque chose
         *     à afficher.
         */
        get: {
            parameters: {
                query: {
                    origin_city_id: number;
                    destination_city_id: number;
                    date: string;
                    passengers?: number;
                    price_min?: number;
                    price_max?: number;
                    /** @description Heure locale minimale, format HH:MM */
                    departure_from?: string;
                    departure_to?: string;
                    agency_ids?: number[];
                    vehicle_type?: components["schemas"]["VehicleType"];
                    only_available?: boolean;
                    /** @description Le prix est un critère important du classement pour le MVP. */
                    sort?: "best" | "price_asc" | "departure_asc" | "duration_asc";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["TripSummary"][];
                            suggestions: components["schemas"]["SearchSuggestions"];
                        };
                    };
                };
                default: components["responses"]["DefaultError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/trips/{reference}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Détail d'un départ */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Référence publique, lisible et non devinable */
                    reference: components["parameters"]["Reference"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TripDetail"];
                    };
                };
                404: components["responses"]["NotFound"];
                default: components["responses"]["DefaultError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/trips/{reference}/seats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Plan des places et disponibilité
         * @description En mode `SEATED`, renvoie le plan complet avec l'état de chaque
         *     siège. En mode `CAPACITY`, `seats` est vide et seuls les compteurs
         *     sont renseignés.
         *
         *     Une place **tenue** par un paiement en cours est indisponible, au
         *     même titre qu'une place vendue.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Référence publique, lisible et non devinable */
                    reference: components["parameters"]["Reference"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SeatMap"];
                    };
                };
                404: components["responses"]["NotFound"];
                default: components["responses"]["DefaultError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Historique des réservations */
        get: {
            parameters: {
                query?: {
                    status?: components["schemas"]["BookingStatus"][];
                    page?: components["parameters"]["Page"];
                    per_page?: components["parameters"]["PerPage"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Booking"][];
                            meta: components["schemas"]["PaginationMeta"];
                        };
                    };
                };
                default: components["responses"]["DefaultError"];
            };
        };
        put?: never;
        /**
         * Créer une réservation et tenir les places
         * @description Opération atomique de prise de places. Elle crée la réservation en
         *     `PENDING_PAYMENT` et renvoie `expires_at`.
         *
         *     Les places sont tenues **dès cet appel**, donc avant la saisie des
         *     informations passagers côté client : tenir la place seulement au
         *     paiement laisserait deux passagers saisir en parallèle et l'un des
         *     deux perdrait sa place au dernier écran.
         *
         *     La durée du hold est de 10 minutes par défaut, paramétrable par
         *     agence. Un échec de paiement **ne libère pas** les places : la
         *     fenêtre court en entier, seule une annulation explicite libère
         *     avant terme.
         *
         *     Une réservation de plusieurs places est prise en tout ou rien.
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    /**
                     * @description Rejouer la même clé renvoie le résultat initial sans créer de
                     *     doublon. Un UUID généré par le client convient.
                     */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        trip_reference: string;
                        passengers: {
                            first_name: string;
                            last_name: string;
                            phone?: string;
                            /**
                             * Format: int64
                             * @description Requis en mode SEATED, ignoré en mode CAPACITY
                             */
                            seat_id?: number | null;
                        }[];
                        /** @description Requis si la réservation est faite pour un tiers */
                        contact_name?: string;
                        contact_phone?: string;
                    };
                };
            };
            responses: {
                /** @description Réservation créée, places tenues */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Booking"];
                    };
                };
                /**
                 * @description Conflit sur l'inventaire ou la fenêtre de vente.
                 *
                 *     Codes possibles — `SEAT_ALREADY_HELD`, `TRIP_FULL`,
                 *     `ONLINE_SALES_CLOSED`, `TRIP_CANCELLED`.
                 */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                422: components["responses"]["ValidationError"];
                default: components["responses"]["DefaultError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/bookings/{reference}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Détail d'une réservation */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Référence publique, lisible et non devinable */
                    reference: components["parameters"]["Reference"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Booking"];
                    };
                };
                404: components["responses"]["NotFound"];
                default: components["responses"]["DefaultError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/bookings/{reference}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Annuler tout ou partie d'une réservation
         * @description Sans `passenger_ids`, la réservation entière est annulée. Avec, seuls
         *     les passagers désignés le sont — l'annulation partielle est
         *     supportée dès le MVP.
         *
         *     Les conditions applicables sont celles **figées sur la réservation**
         *     à sa création : un durcissement ultérieur des conditions de l'agence
         *     est sans effet.
         *
         *     Le remboursement part toujours vers le compte source du paiement.
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    /**
                     * @description Rejouer la même clé renvoie le résultat initial sans créer de
                     *     doublon. Un UUID généré par le client convient.
                     */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path: {
                    /** @description Référence publique, lisible et non devinable */
                    reference: components["parameters"]["Reference"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        passenger_ids?: number[];
                    };
                };
            };
            responses: {
                /** @description Annulation enregistrée */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            booking: components["schemas"]["Booking"];
                            refund: components["schemas"]["Refund"] | null;
                        };
                    };
                };
                /**
                 * @description Codes possibles — `CANCELLATION_DEADLINE_PASSED`,
                 *     `BOOKING_NOT_CANCELLABLE`.
                 */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                default: components["responses"]["DefaultError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/bookings/{reference}/cancellation-quote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Simuler une annulation
         * @description Renvoie le montant remboursable et les frais retenus, sans rien
         *     exécuter. Permet d'afficher au passager ce qu'il récupérera avant
         *     qu'il confirme.
         */
        get: {
            parameters: {
                query?: {
                    passenger_ids?: number[];
                };
                header?: never;
                path: {
                    /** @description Référence publique, lisible et non devinable */
                    reference: components["parameters"]["Reference"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CancellationQuote"];
                    };
                };
                default: components["responses"]["DefaultError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/bookings/{reference}/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Initier un paiement
         * @description Le paiement Mobile Money est **asynchrone** : le passager reçoit une
         *     sollicitation sur son téléphone et doit saisir son code. La réponse
         *     est donc `PENDING` ou `PROCESSING`, jamais `SUCCEEDED` immédiatement.
         *
         *     Le client suit ensuite l'état par `GET /v1/payments/{reference}` ou
         *     par notification.
         *
         *     Une réservation porte **plusieurs tentatives**, dont une seule
         *     aboutie. Réessayer après un échec est le cas nominal.
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    /**
                     * @description Rejouer la même clé renvoie le résultat initial sans créer de
                     *     doublon. Un UUID généré par le client convient.
                     */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path: {
                    /** @description Référence publique, lisible et non devinable */
                    reference: components["parameters"]["Reference"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        method: components["schemas"]["PaymentMethod"];
                        /**
                         * @description Requis si method = MOBILE_MONEY
                         * @enum {string}
                         */
                        operator?: "MTN" | "ORANGE";
                        /**
                         * @description Compte débité. Le remboursement éventuel retournera
                         *     toujours vers ce compte, jamais vers un numéro déclaré
                         *     après coup.
                         */
                        payer_phone?: string;
                    };
                };
            };
            responses: {
                /** @description Paiement initié */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Payment"];
                    };
                };
                /** @description Codes possibles — `PAYMENT_ALREADY_SUCCEEDED`, `BOOKING_EXPIRED`. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                default: components["responses"]["DefaultError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/payments/{reference}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** État d'un paiement */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Référence publique, lisible et non devinable */
                    reference: components["parameters"]["Reference"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Payment"];
                    };
                };
                404: components["responses"]["NotFound"];
                default: components["responses"]["DefaultError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/webhooks/payments/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Notification de l'agrégateur
         * @description Appelé par le prestataire de paiement. Le traitement est
         *     **idempotent** : le couple `(provider, event_id)` est unique, un
         *     rejeu ne produit aucun doublon.
         *
         *     Chaque appel est journalisé — reçu, rejoué, échoué — ce qui rend un
         *     paiement perdu débogable.
         *
         *     Cas particulier : si le succès arrive **après** l'expiration du hold
         *     et que la place a été revendue, un remboursement intégral est
         *     déclenché automatiquement avec le motif `LATE_PAYMENT`.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    provider: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            responses: {
                /** @description Reçu */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Signature invalide */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                default: components["responses"]["DefaultError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Billets du passager */
        get: {
            parameters: {
                query?: {
                    page?: components["parameters"]["Page"];
                    per_page?: components["parameters"]["PerPage"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Ticket"][];
                            meta: components["schemas"]["PaginationMeta"];
                        };
                    };
                };
                default: components["responses"]["DefaultError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tickets/{reference}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Détail d'un billet
         * @description La réponse porte `qr_payload`, à partir duquel le client **regénère
         *     le QR Code localement**. Il n'est jamais téléchargé comme image : un
         *     billet dont le QR ne s'affiche pas en gare ne vaut rien.
         *
         *     Le billet est mis en cache par le client et reste consultable sans
         *     réseau.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Référence publique, lisible et non devinable */
                    reference: components["parameters"]["Reference"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Ticket"];
                    };
                };
                404: components["responses"]["NotFound"];
                default: components["responses"]["DefaultError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agency/trips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Départs de l'agence
         * @description Portée au rôle `AGENT` ou `AGENCY`, limitée à l'agence de l'utilisateur.
         */
        get: {
            parameters: {
                query?: {
                    from?: string;
                    to?: string;
                    page?: components["parameters"]["Page"];
                    per_page?: components["parameters"]["PerPage"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["TripSummary"][];
                            meta: components["schemas"]["PaginationMeta"];
                        };
                    };
                };
                default: components["responses"]["DefaultError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agency/trips/{reference}/boarding-list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liste d'embarquement
         * @description Téléchargée **avant le départ** et conservée localement par la PWA.
         *     Les scans sont ensuite vérifiés hors ligne contre cette liste.
         *
         *     `generated_at` permet à l'agent de savoir si sa copie est fraîche.
         *
         *     La fermeture des ventes en ligne 30 minutes avant le départ et le
         *     délai limite d'annulation passager font qu'aucun passager ne peut
         *     annuler entre le téléchargement et l'embarquement : le risque de
         *     liste périmée se limite aux actions de l'agence.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Référence publique, lisible et non devinable */
                    reference: components["parameters"]["Reference"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BoardingList"];
                    };
                };
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                default: components["responses"]["DefaultError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agency/trips/{reference}/validations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Synchroniser les validations
         * @description Envoi groupé des validations mises en file hors ligne, avec un
         *     **résultat par élément**.
         *
         *     Ce n'est délibérément pas du tout-ou-rien : un doublon ne doit pas
         *     faire échouer les quarante autres validations du même car. La
         *     réponse renvoie donc `200` même lorsque certains éléments sont
         *     rejetés, et chaque résultat porte son propre statut.
         *
         *     `client_id` est un identifiant local à l'appareil : il permet au
         *     client de corréler les résultats et de purger sa file.
         *
         *     **La double validation hors ligne est un coût accepté.** Deux agents
         *     disposant de la liste peuvent valider le même billet ; le serveur la
         *     signale plutôt que de la bloquer, les deux agents relevant de la
         *     même agence.
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    /**
                     * @description Rejouer la même clé renvoie le résultat initial sans créer de
                     *     doublon. Un UUID généré par le client convient.
                     */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path: {
                    /** @description Référence publique, lisible et non devinable */
                    reference: components["parameters"]["Reference"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        device_id?: string;
                        validations: {
                            /** @description Identifiant local, corrélation et purge de la file */
                            client_id: string;
                            ticket_reference: string;
                            /**
                             * Format: date-time
                             * @description Horodatage de l'appareil, l'agent pouvant être hors ligne
                             */
                            validated_at: string;
                            method: components["schemas"]["ValidationMethod"];
                        }[];
                    };
                };
            };
            responses: {
                /** @description Synchronisation traitée, résultat par élément */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            results: components["schemas"]["ValidationResult"][];
                        };
                    };
                };
                default: components["responses"]["DefaultError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agency/tickets/lookup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Vérifier un billet en ligne
         * @description Secours utilisé lorsque l'agent dispose du réseau — saisie manuelle
         *     d'une référence, ou levée de doute sur un cas affiché par la PWA.
         *
         *     Les cinq issues sont distinctes : un simple « invalide » est
         *     inexploitable pour l'agent, qui doit savoir **pourquoi**.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Référence du billet ou de la réservation */
                        reference: string;
                        trip_reference: string;
                    };
                };
            };
            responses: {
                /** @description Billet valide */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BoardingPassenger"];
                    };
                };
                /** @description Référence inconnue — code `TICKET_NOT_FOUND` */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /**
                 * @description Codes possibles — `TICKET_ALREADY_VALIDATED`, `TICKET_WRONG_TRIP`,
                 *     `TICKET_CANCELLED`.
                 */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                default: components["responses"]["DefaultError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agency/stations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Gares de l'agence */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["AgencyStation"][];
                        };
                    };
                };
                default: components["responses"]["DefaultError"];
            };
        };
        put?: never;
        /**
         * Créer une gare
         * @description La gare **appartient à l'agence** et est publiée immédiatement : la
         *     modération est a posteriori, car bloquer une agence motivée pendant
         *     plusieurs jours la ferait renoncer.
         *
         *     La ville, elle, vient du **référentiel fermé** curé par MOTOBOY : si
         *     chaque agence pouvait créer la sienne, « Douala », « douala » et « Dla »
         *     coexisteraient et la recherche cesserait de regrouper les offres.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AgencyStationInput"];
                };
            };
            responses: {
                /** @description Gare créée */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AgencyStation"];
                    };
                };
                422: components["responses"]["ValidationError"];
                default: components["responses"]["DefaultError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agency/stations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Modifier une gare */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ResourceId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name?: string;
                        address?: string | null;
                        latitude?: number | null;
                        longitude?: number | null;
                        is_active?: boolean;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AgencyStation"];
                    };
                };
                404: components["responses"]["NotFound"];
                default: components["responses"]["DefaultError"];
            };
        };
        trace?: never;
    };
    "/v1/agency/city-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Demander l'ajout d'une ville
         * @description Sans ce circuit, une agence desservant une ville absente du référentiel
         *     est bloquée sans recours et abandonne.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: int64 */
                        country_id: number;
                        requested_name: string;
                    };
                };
            };
            responses: {
                /** @description Demande enregistrée */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: int64 */
                            id: number;
                            requested_name: string;
                            /** @enum {string} */
                            status: "PENDING" | "APPROVED" | "REJECTED";
                        };
                    };
                };
                default: components["responses"]["DefaultError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agency/vehicles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Véhicules de l'agence */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["AgencyVehicle"][];
                        };
                    };
                };
                default: components["responses"]["DefaultError"];
            };
        };
        put?: never;
        /**
         * Enregistrer un véhicule
         * @description En mode `SEATED`, le **plan de sièges est généré** à partir de la
         *     capacité : demander à une agence de créer trente sièges un par un
         *     garantirait qu'elle ne le fasse pas, et sans plan le passager ne peut
         *     pas choisir sa place.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AgencyVehicleInput"];
                };
            };
            responses: {
                /** @description Véhicule enregistré */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AgencyVehicle"];
                    };
                };
                422: components["responses"]["ValidationError"];
                default: components["responses"]["DefaultError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agency/vehicles/{id}/seats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Plan de sièges d'un véhicule */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ResourceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Vide en mode CAPACITY */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["AgencySeat"][];
                        };
                    };
                };
                404: components["responses"]["NotFound"];
                default: components["responses"]["DefaultError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agency/drivers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Chauffeurs de l'agence */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["AgencyDriver"][];
                        };
                    };
                };
                default: components["responses"]["DefaultError"];
            };
        };
        put?: never;
        /**
         * Enregistrer un chauffeur
         * @description Le chauffeur reste un acteur métier **sans application dédiée**. Il peut
         *     en revanche porter le rôle `AGENT` pour l'embarquement : le rôle est
         *     fonctionnel, pas lié à un métier.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AgencyDriverInput"];
                };
            };
            responses: {
                /** @description Chauffeur enregistré */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AgencyDriver"];
                    };
                };
                422: components["responses"]["ValidationError"];
                default: components["responses"]["DefaultError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agency/routes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Itinéraires de l'agence */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["AgencyRoute"][];
                        };
                    };
                };
                default: components["responses"]["DefaultError"];
            };
        };
        put?: never;
        /**
         * Créer un itinéraire
         * @description Un itinéraire n'est **jamais daté** — un départ l'est toujours. Les
         *     gares de départ et d'arrivée doivent appartenir à l'agence.
         *
         *     Les escales sont **purement informatives** : la réservation est
         *     point-à-point, et une ville d'escale ne rend pas un départ éligible à
         *     une recherche qui la viserait.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AgencyRouteInput"];
                };
            };
            responses: {
                /** @description Itinéraire créé */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AgencyRoute"];
                    };
                };
                404: components["responses"]["NotFound"];
                422: components["responses"]["ValidationError"];
                default: components["responses"]["DefaultError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agency/routes/{routeId}/schedules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Créer un horaire récurrent
         * @description Sans horaires récurrents, une agence ressaisit ses départs chaque matin
         *     et abandonne au bout d'une semaine — l'application afficherait alors des
         *     données mortes, ce qui tue un comparateur plus sûrement qu'une absence
         *     d'offre.
         *
         *     Modifier un horaire **n'affecte pas les départs déjà générés** : le
         *     changement s'applique aux départs créés ensuite.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    routeId: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AgencyScheduleInput"];
                };
            };
            responses: {
                /** @description Horaire créé */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AgencySchedule"];
                    };
                };
                404: components["responses"]["NotFound"];
                422: components["responses"]["ValidationError"];
                default: components["responses"]["DefaultError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agency/trips/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Générer les départs manquants
         * @description Génère sur l'horizon glissant, **sans jamais modifier un départ
         *     existant** : une régénération qui les écraserait réécrirait des départs
         *     portant déjà des réservations.
         *
         *     Exposé pour que l'agence voie immédiatement l'effet d'un horaire qu'elle
         *     vient de créer ; un job quotidien fait avancer la fenêtre.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            created: number;
                            horizon_days: number;
                        };
                    };
                };
                default: components["responses"]["DefaultError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agency/counter-sales": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Vendre au guichet
         * @description **Le critère est la vitesse.** Si saisir une vente au comptoir prend plus
         *     de temps que d'écrire une ligne dans le cahier, l'agence ne le fera pas —
         *     et toute la fiabilité de la disponibilité affichée s'effondre. D'où un
         *     seul appel : départ, places, nom et téléphone.
         *
         *     Trois conséquences, toutes délibérées :
         *
         *     - **le passager n'a pas de compte** — ni inscription ni OTP ;
         *     - la réservation est créée directement en `CONFIRMED`, **sans tenue ni
         *       tunnel de paiement** : l'argent est déjà dans la caisse ;
         *     - un paiement de méthode `CASH` est enregistré, **sans transiter par
         *       l'agrégateur**, pour que statistiques et compte courant restent
         *       cohérents.
         *
         *     La vente au guichet reste ouverte **jusqu'au départ**, alors que la vente
         *     en ligne ferme trente minutes avant : l'agence voit le véhicule et
         *     maîtrise sa situation.
         *
         *     Une place tenue par un paiement en ligne en cours reste indisponible ici,
         *     au même titre qu'une place vendue.
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    /**
                     * @description Rejouer la même clé renvoie le résultat initial sans créer de
                     *     doublon. Un UUID généré par le client convient.
                     */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CounterSaleInput"];
                };
            };
            responses: {
                /** @description Vente enregistrée, billets émis */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CounterSale"];
                    };
                };
                /** @description Codes possibles — `SEAT_ALREADY_HELD`, `TRIP_FULL`, `TRIP_CANCELLED`. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                422: components["responses"]["ValidationError"];
                default: components["responses"]["DefaultError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agency/trips/{reference}/seats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Plan des places, vu du guichet
         * @description Identique au plan public, à une différence près : les places **tenues**
         *     portent leur échéance.
         *
         *     Le hold l'emporte sur le guichet — donner la priorité au comptoir
         *     obligerait à rembourser un passager venant de payer avec succès. Mais
         *     l'agent doit distinguer « vendue » de « tenue, se libère dans six
         *     minutes » pour savoir s'il attend ou s'il oriente son client vers un
         *     autre siège.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Référence publique, lisible et non devinable */
                    reference: components["parameters"]["Reference"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CounterSeatMap"];
                    };
                };
                404: components["responses"]["NotFound"];
                default: components["responses"]["DefaultError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CounterSaleInput: {
            trip_reference: string;
            passengers: {
                first_name: string;
                last_name: string;
                /**
                 * Format: int64
                 * @description Requis en mode SEATED, ignoré en mode CAPACITY.
                 */
                seat_id?: number | null;
            }[];
            /**
             * @description Destinataire du billet par SMS. Aucun compte n'est créé : c'est une
             *     vente au comptoir, pas un tunnel de conversion.
             */
            contact_phone: string;
            contact_name?: string | null;
        };
        CounterSale: {
            booking: components["schemas"]["Booking"];
            amount_due: components["schemas"]["Money"];
            ticket_references: string[];
            /**
             * @description Faux si l'agence a désactivé l'envoi. C'est le seul cas où la
             *     plateforme paierait un SMS sur une vente ne portant aucune
             *     commission, d'où le levier.
             */
            sms_sent: boolean;
        };
        CounterSeatMap: {
            seating_mode: components["schemas"]["SeatingMode"];
            capacity: number;
            seats_available: number;
            seats: components["schemas"]["CounterSeat"][];
        };
        CounterSeat: components["schemas"]["Seat"] & {
            /**
             * Format: date-time
             * @description Renseigné pour une place au statut HELD.
             */
            held_until?: string | null;
        };
        AgencyStation: {
            /** Format: int64 */
            id: number;
            name: string;
            city?: string | null;
            /** Format: int64 */
            city_id: number;
            address?: string | null;
            latitude?: number | null;
            longitude?: number | null;
            is_active: boolean;
            /**
             * Format: date-time
             * @description Modération a posteriori — la gare est publiée sans l'attendre.
             */
            moderated_at?: string | null;
        };
        AgencyStationInput: {
            /**
             * Format: int64
             * @description Issue du référentiel fermé curé par MOTOBOY.
             */
            city_id: number;
            name: string;
            address?: string | null;
            latitude?: number | null;
            longitude?: number | null;
        };
        AgencyVehicle: {
            /** Format: int64 */
            id: number;
            registration: string;
            brand?: string | null;
            model?: string | null;
            type: components["schemas"]["VehicleType"];
            seating_mode: components["schemas"]["SeatingMode"];
            capacity: number;
            seats_count?: number | null;
            condition?: string;
        };
        AgencyVehicleInput: {
            registration: string;
            brand?: string | null;
            model?: string | null;
            type: components["schemas"]["VehicleType"];
            seating_mode: components["schemas"]["SeatingMode"];
            capacity: number;
            /**
             * @description Rattache le véhicule à un propriétaire. Son accès reste en
             *     consultation seule, sans aucun circuit financier porté par la
             *     plateforme.
             */
            owner_phone?: string | null;
        };
        AgencySeat: {
            /** Format: int64 */
            id: number;
            label: string;
            row_index?: number;
            column_index?: number;
            is_bookable: boolean;
        };
        AgencyDriver: {
            /** Format: int64 */
            id: number;
            first_name: string;
            last_name: string;
            phone: string;
            license_number: string;
            /** Format: date */
            license_expires_at?: string | null;
            /** Format: int64 */
            assigned_vehicle_id?: number | null;
            status: string;
        };
        AgencyDriverInput: {
            first_name: string;
            last_name: string;
            phone: string;
            license_number: string;
            /** Format: date */
            license_expires_at?: string | null;
            /** Format: int64 */
            assigned_vehicle_id?: number | null;
        };
        AgencyRoute: {
            /** Format: int64 */
            id: number;
            origin: components["schemas"]["AgencyRouteEnd"];
            destination: components["schemas"]["AgencyRouteEnd"];
            reference_duration_minutes?: number | null;
            /** @description Informatives — jamais réservables. */
            stops: {
                city?: string | null;
                position: number;
            }[];
            schedules: components["schemas"]["AgencySchedule"][];
            is_active: boolean;
        };
        AgencyRouteEnd: {
            city?: string | null;
            station?: string | null;
        };
        AgencyRouteInput: {
            /** Format: int64 */
            origin_station_id: number;
            /** Format: int64 */
            destination_station_id: number;
            reference_duration_minutes?: number | null;
            stops?: number[];
        };
        AgencySchedule: {
            /** Format: int64 */
            id: number;
            /** @description Heure locale de pendule, pas un instant. */
            departure_time: string;
            days_of_week: number[];
            /** Format: int64 */
            default_vehicle_id?: number | null;
            /** Format: int64 */
            default_driver_id?: number | null;
            price: components["schemas"]["Money"];
            /** Format: date */
            valid_from: string;
            /** Format: date */
            valid_until?: string | null;
            is_active: boolean;
        };
        AgencyScheduleInput: {
            /** @example 08:00 */
            departure_time: string;
            days_of_week: number[];
            /** Format: int64 */
            default_vehicle_id: number;
            /** Format: int64 */
            default_driver_id?: number | null;
            price: number;
            /** Format: date */
            valid_from: string;
            /** Format: date */
            valid_until?: string | null;
        };
        /**
         * @description Un OTP est lié à son intention : un code demandé pour se connecter ne
         *     doit pas pouvoir valider une inscription.
         * @enum {string}
         */
        OtpPurpose: "REGISTRATION" | "LOGIN" | "PHONE_CHANGE";
        /**
         * @description Le Cameroun a deux langues officielles, et les régions du Nord-Ouest
         *     et du Sud-Ouest sont anglophones — Bamenda, Buea, Limbe sont des
         *     destinations interurbaines réelles. Les deux langues sont donc
         *     servies dès le lancement, pas à l'expansion.
         *
         *     Résolution : `users.locale` pour un compte, langue par défaut de
         *     l'agence pour un passager de vente au guichet, qui n'a pas de compte.
         * @enum {string}
         */
        Locale: "fr" | "en";
        /**
         * @description Code typé, sur lequel les clients branchent. `message` est destiné à
         *     l'affichage et peut changer sans préavis.
         * @enum {string}
         */
        ErrorCode: "VALIDATION_FAILED" | "UNAUTHENTICATED" | "FORBIDDEN" | "NOT_FOUND" | "RATE_LIMITED" | "OTP_INVALID" | "OTP_EXPIRED" | "OTP_TOO_MANY_ATTEMPTS" | "SEAT_ALREADY_HELD" | "TRIP_FULL" | "ONLINE_SALES_CLOSED" | "TRIP_CANCELLED" | "BOOKING_EXPIRED" | "BOOKING_NOT_CANCELLABLE" | "CANCELLATION_DEADLINE_PASSED" | "PAYMENT_ALREADY_SUCCEEDED" | "PAYMENT_FAILED" | "TICKET_NOT_FOUND" | "TICKET_ALREADY_VALIDATED" | "TICKET_WRONG_TRIP" | "TICKET_CANCELLED";
        Error: {
            code: components["schemas"]["ErrorCode"];
            /**
             * @description **Diagnostic — ne jamais afficher à l'utilisateur.**
             *
             *     Destiné aux journaux, à l'exploitation et au débogage. Sa langue
             *     n'est pas garantie et son libellé peut changer sans préavis.
             *
             *     Le client rend le message affiché à partir de `code` et de
             *     `details`, dans la langue de l'utilisateur. C'est ce qui permet à
             *     la localisation des erreurs de rester entièrement côté client,
             *     sans négociation `Accept-Language`.
             */
            message: string;
            /**
             * @description Valeurs d'interpolation du message affiché — échéance dépassée,
             *     sièges en conflit, etc.
             */
            details?: {
                [key: string]: unknown;
            };
        };
        ValidationErrorBody: {
            code: components["schemas"]["ErrorCode"];
            /** @description Diagnostic — ne jamais afficher. Voir `Error.message`. */
            message: string;
            errors: {
                [key: string]: string[];
            };
        };
        PaginationMeta: {
            page: number;
            per_page: number;
            total: number;
            last_page: number;
        };
        /**
         * @description Il n'existe pas d'état `FAILED` : l'échec appartient à la tentative
         *     de paiement, pas à la réservation.
         * @enum {string}
         */
        BookingStatus: "PENDING_PAYMENT" | "CONFIRMED" | "EXPIRED" | "CANCELLED_BY_PASSENGER" | "CANCELLED_BY_AGENCY" | "USED" | "NO_SHOW";
        /** @enum {string} */
        PaymentStatus: "PENDING" | "PROCESSING" | "SUCCEEDED" | "FAILED";
        /** @enum {string} */
        PaymentMethod: "MOBILE_MONEY" | "CARD" | "CASH";
        /** @enum {string} */
        RefundStatus: "PENDING" | "PROCESSING" | "COMPLETED" | "FAILED";
        /** @enum {string} */
        RefundReason: "PASSENGER_REQUEST" | "AGENCY_TRIP_CANCELLED" | "TRIP_MODIFIED" | "LATE_PAYMENT" | "DUPLICATE_PAYMENT" | "ADMIN_ADJUSTMENT";
        /** @enum {string} */
        TicketStatus: "VALID" | "USED" | "CANCELLED";
        /** @enum {string} */
        ValidationMethod: "SCAN" | "MANUAL";
        /** @enum {string} */
        SeatingMode: "SEATED" | "CAPACITY";
        /** @enum {string} */
        VehicleType: "BUS" | "CAR";
        User: {
            /** Format: int64 */
            id: number;
            phone: string;
            /** Format: email */
            email?: string | null;
            first_name: string;
            last_name: string;
            phone_verified?: boolean;
            locale?: components["schemas"]["Locale"];
        };
        OtpChallenge: {
            /**
             * Format: date-time
             * @description Validité de 10 minutes
             */
            expires_at: string;
            /** @description 4 tentatives au maximum */
            attempts_remaining: number;
        };
        PlaceSuggestion: {
            /** @enum {string} */
            type: "CITY" | "STATION";
            /**
             * Format: int64
             * @description Cible de la recherche, y compris lorsque le type est STATION
             */
            city_id: number;
            /** Format: int64 */
            station_id?: number | null;
            label: string;
            /** @description Ville de rattachement, lorsque la suggestion est une gare */
            secondary_label?: string | null;
        };
        Money: {
            /**
             * Format: int64
             * @description Unités entières de devise, le XAF n'ayant pas de subdivision
             */
            amount: number;
            currency: string;
        };
        AgencySummary: {
            /** Format: int64 */
            id: number;
            name: string;
            logo_url?: string | null;
        };
        StationSummary: {
            /** Format: int64 */
            id: number;
            name: string;
            city: string;
            address?: string | null;
            latitude?: number | null;
            longitude?: number | null;
        };
        /**
         * @description Conditions **figées sur la réservation**. Affichées avant le
         *     paiement ; un durcissement ultérieur des conditions de l'agence est
         *     sans effet sur les réservations existantes.
         */
        CancellationPolicy: {
            deadline_hours: number;
            /** @enum {string} */
            fee_type: "PERCENTAGE" | "FIXED";
            /** Format: int64 */
            fee_value: number;
        };
        TripSummary: {
            reference: string;
            agency: components["schemas"]["AgencySummary"];
            /** Format: date-time */
            departure_at: string;
            /** Format: date-time */
            arrival_estimate_at?: string | null;
            duration_minutes?: number | null;
            origin_station: components["schemas"]["StationSummary"];
            destination_station: components["schemas"]["StationSummary"];
            price: components["schemas"]["Money"];
            seats_available: number;
            capacity?: number;
            seating_mode: components["schemas"]["SeatingMode"];
            vehicle_type: components["schemas"]["VehicleType"];
            /**
             * @description Escales **purement informatives**. La réservation est
             *     point-à-point : une ville d'escale ne rend pas ce trajet
             *     éligible à une recherche qui la viserait.
             */
            stops?: {
                city: string;
                position: number;
            }[];
            cancellation_policy?: components["schemas"]["CancellationPolicy"];
            /** Format: date-time */
            online_sales_close_at?: string;
        };
        TripDetail: components["schemas"]["TripSummary"] & {
            vehicle?: {
                brand?: string | null;
                model?: string | null;
                type?: components["schemas"]["VehicleType"];
            };
        };
        Seat: {
            /** Format: int64 */
            id: number;
            label: string;
            row_index?: number;
            column_index?: number;
            /**
             * @description `HELD` désigne une place tenue par un paiement en cours. Elle est
             *     indisponible au même titre qu'une place vendue, sur tous les
             *     canaux — vente au guichet comprise.
             * @enum {string}
             */
            status: "AVAILABLE" | "TAKEN" | "HELD" | "UNAVAILABLE";
        };
        SeatMap: {
            seating_mode: components["schemas"]["SeatingMode"];
            capacity: number;
            seats_available: number;
            /** @description Vide en mode CAPACITY */
            seats: components["schemas"]["Seat"][];
        };
        /**
         * @description Repli affiché lorsque la recherche ne renvoie rien. Une couverture
         *     encore faible au lancement rendra ce cas fréquent, et un passager
         *     déçu deux fois ne revient pas.
         */
        SearchSuggestions: {
            nearby_dates: {
                /** Format: date */
                date: string;
                trips_count: number;
                lowest_price: components["schemas"]["Money"];
            }[];
            /** @description Axes desservis au départ de la même ville */
            routes_served: {
                /** Format: int64 */
                destination_city_id: number;
                destination_city: string;
                trips_count: number;
            }[];
        };
        BookingPassenger: {
            /** Format: int64 */
            id: number;
            first_name: string;
            last_name: string;
            phone?: string | null;
            seat_label?: string | null;
            /** @enum {string} */
            status: "ACTIVE" | "CANCELLED";
            ticket_reference?: string | null;
        };
        Booking: {
            reference: string;
            status: components["schemas"]["BookingStatus"];
            /**
             * Format: date-time
             * @description Échéance du hold. Renseignée tant que la réservation est en
             *     `PENDING_PAYMENT`. Le client affiche un compte à rebours : le
             *     passager doit savoir qu'il est chronométré.
             */
            expires_at?: string | null;
            trip: components["schemas"]["TripSummary"];
            passengers: components["schemas"]["BookingPassenger"][];
            seats_count: number;
            total: components["schemas"]["Money"];
            cancellation_policy?: components["schemas"]["CancellationPolicy"];
            contact_name?: string | null;
            contact_phone?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            confirmed_at?: string | null;
        };
        Payment: {
            reference: string;
            booking_reference?: string;
            status: components["schemas"]["PaymentStatus"];
            method: components["schemas"]["PaymentMethod"];
            operator?: string | null;
            amount: components["schemas"]["Money"];
            failure_reason?: string | null;
            /** Format: date-time */
            paid_at?: string | null;
            /** Format: date-time */
            created_at?: string;
        };
        Refund: {
            reference: string;
            status: components["schemas"]["RefundStatus"];
            reason: components["schemas"]["RefundReason"];
            amount: components["schemas"]["Money"];
            /** Format: date-time */
            completed_at?: string | null;
        };
        CancellationQuote: {
            cancellable: boolean;
            /** @description Code d'erreur qui serait renvoyé, si `cancellable` est faux */
            reason_if_not?: string | null;
            refundable: components["schemas"]["Money"];
            fee: components["schemas"]["Money"];
            /** Format: date-time */
            deadline_at?: string;
        };
        Ticket: {
            reference: string;
            status: components["schemas"]["TicketStatus"];
            booking_reference?: string;
            passenger_name: string;
            seat_label?: string | null;
            trip: components["schemas"]["TripSummary"];
            /**
             * @description Contenu à encoder. Le client **regénère le QR Code localement**
             *     à partir de cette valeur, il ne le télécharge jamais comme
             *     image. Le billet reste ainsi consultable sans réseau.
             */
            qr_payload: string;
            /** Format: date-time */
            issued_at?: string;
        };
        BoardingPassenger: {
            ticket_reference: string;
            booking_reference?: string;
            passenger_name: string;
            seat_label?: string | null;
            status: components["schemas"]["TicketStatus"];
            /** @description Nombre de billets de la même réservation */
            group_size?: number;
            /**
             * @description Billets déjà validés dans cette réservation. Permet d'afficher
             *     « 2/3 validés » pour que l'agent sache qui manque encore.
             */
            group_validated?: number;
            /** Format: date-time */
            validated_at?: string | null;
        };
        BoardingList: {
            trip: components["schemas"]["TripSummary"];
            /**
             * Format: date-time
             * @description Permet à l'agent de juger la fraîcheur de sa copie locale
             */
            generated_at: string;
            passengers: components["schemas"]["BoardingPassenger"][];
        };
        ValidationResult: {
            /** @description Repris de la requête, pour corréler et purger la file locale */
            client_id: string;
            ticket_reference: string;
            /** @enum {string} */
            status: "ACCEPTED" | "DUPLICATE" | "REJECTED";
            code?: components["schemas"]["ErrorCode"] | null;
            /**
             * Format: date-time
             * @description Renseigné lorsque le statut est DUPLICATE
             */
            first_validated_at?: string | null;
        };
    };
    responses: {
        /**
         * @description Réponse d'erreur par défaut, déclarée sur **toutes** les opérations.
         *
         *     Sans elle, une opération n'ayant que des réponses `2xx` produit un
         *     type d'erreur `never` dans le client généré : le consommateur ne peut
         *     alors pas traiter l'échec de façon typée, alors qu'un `401`, un `429`
         *     ou un `500` restent toujours possibles.
         */
        DefaultError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Jeton absent ou invalide */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Permission insuffisante pour la ressource demandée */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Ressource introuvable */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Corps de requête invalide */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ValidationErrorBody"];
            };
        };
    };
    parameters: {
        /** @description Référence publique, lisible et non devinable */
        Reference: string;
        ResourceId: number;
        /**
         * @description Rejouer la même clé renvoie le résultat initial sans créer de
         *     doublon. Un UUID généré par le client convient.
         */
        IdempotencyKey: string;
        Page: number;
        PerPage: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
